deploy:
  provider: npm
  email: marta.gajowczyk@vizzuality.com
  api_key:
    secure: cu3ePQixmXch09A8nG3qgu3Zr1OnijTjtiOj/BEj81FHsZWyaDS+5K+WjGRoMVA2+Pmg8Ypvdgj8b8axww3cdOZ4sj/zzE9WaAAi5UiAYH0qGQL2tjPjTjwmeAw5Hhxb1HGYjTeCTiYfu4GEv0qRY6m2jNQtXHooINmRuyql2M1nBUibsPEyirtAhRsraveP7uxSt5A2TC3nPIIkejWxIby2HjNneCeTbcd0oWtdfs4qJit1eexzWO8UvZBie4XLVpwrIhKcdVzZT7m+cOAjzoi+UNCFdfkZSHYWk2iI4dYn4zPe2Ob6hOHlJdOEkZ0bTNPjLeWFz2lwvtug7+0hZ4Dxj4GvZGOdeza0h3FmOCsMG7eCDg4ZZvzGO5u0iOOPDI1LODSG7UMn1p8CYK1YxcPrjKPnNpYsOOTo9BH0EkMeCQk/TlGBHAcM/yCIbvktJAgDMu6aUfycwX4M6sfiNxs1I41J8FQDxX2R9ydcXsGz+6NftgzGqlnC6588qfmRXVGnfyzyg8BQ0U9/y1pBFJP9kKsZXzuKpqVqk+6TTfm0kCm7N5ml1qzzmprwkOp7lJKBAb7QE2BJDCS6B+PV2VKDEeddVUefKtzDySKm+J4+oCjJfC+vzx5/5EjWz6rTjqp+iN26lBlYrNWujh+kypRliOp9m3nXLZVrNCab3GM=
  on:
    tags: true
    branch: master
    repo: Vizzuality/gfw-components
